# -*- coding: utf-8 -*-
"""Abdulla Khalid Al Ali - Assingment 1 ( ICS 220 )

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fcgSUnZrgot4QLEw3SPaz1OHB6Tu08kM
"""

class Passenger:
    def __init__(self, passenger_id, first_name, last_name, date_of_birth, email):
        self._passenger_id = passenger_id
        self._first_name = first_name
        self._last_name = last_name
        self._date_of_birth = date_of_birth
        self._email = email

    # Getter and Setter methods for Passenger ID
    def get_passenger_id(self):
        return self._passenger_id

    def set_passenger_id(self, passenger_id):
        self._passenger_id = passenger_id

    # Getter and Setter methods for First Name
    def get_first_name(self):
        return self._first_name

    def set_first_name(self, first_name):
        self._first_name = first_name

    # Getter and Setter methods for Last Name
    def get_last_name(self):
        return self._last_name

    def set_last_name(self, last_name):
        self._last_name = last_name

    # Getter and Setter methods for Date of Birth
    def get_date_of_birth(self):
        return self._date_of_birth

    def set_date_of_birth(self, date_of_birth):
        self._date_of_birth = date_of_birth

    # Getter and Setter methods for Email
    def get_email(self):
        return self._email

    def set_email(self, email):
        self._email = email

    def get_full_name(self):
        return f"{self._first_name} {self._last_name}"


class BoardingPass:
    def __init__(self, boarding_pass_id, passenger_name, from_location, to_location, flight):
        self._boarding_pass_id = boarding_pass_id
        self._passenger_name = passenger_name
        self._from_location = from_location
        self._to_location = to_location
        self._flight = flight

    # Getter and Setter methods for Boarding Pass ID
    def get_boarding_pass_id(self):
        return self._boarding_pass_id

    def set_boarding_pass_id(self, boarding_pass_id):
        self._boarding_pass_id = boarding_pass_id

    # Getter and Setter methods for Passenger Name
    def get_passenger_name(self):
        return self._passenger_name

    def set_passenger_name(self, passenger_name):
        self._passenger_name = passenger_name

    # Getter and Setter methods for From Location
    def get_from_location(self):
        return self._from_location

    def set_from_location(self, from_location):
        self._from_location = from_location

    # Getter and Setter methods for To Location
    def get_to_location(self):
        return self._to_location

    def set_to_location(self, to_location):
        self._to_location = to_location

    # Getter and Setter methods for Flight
    def get_flight(self):
        return self._flight

    def set_flight(self, flight):
        self._flight = flight

    def display_details(self):
        print("NATIONAL AIRLINES")
        print("PASSENGER TICKET AND BAGGAGE CHECK")
        print("\nBOARDING PASS")
        print("FIRST CLASS\n")
        print("Passenger")
        print(self._passenger_name)
        print("From:")
        print(self._from_location)
        print("\nFlight")
        print(self._flight.get_flight_number())
        self._flight.display_additional_details()


class Flight:
    def __init__(self, flight_number, departure_city, destination_city, departure_time, arrival_time,
                 gate, date, time, boarding_till, seat, electronic_ticket, arrival_time2, terminal):
        self._flight_number = flight_number
        self._departure_city = departure_city
        self._destination_city = destination_city
        self._departure_time = departure_time
        self._arrival_time = arrival_time
        self._gate = gate
        self._date = date
        self._time = time
        self._boarding_till = boarding_till
        self._seat = seat
        self._electronic_ticket = electronic_ticket
        self._arrival_time2 = arrival_time2
        self._terminal = terminal

    # Getter and Setter methods for Flight Number
    def get_flight_number(self):
        return self._flight_number

    def set_flight_number(self, flight_number):
        self._flight_number = flight_number

    # Getter and Setter methods for Departure City
    def get_departure_city(self):
        return self._departure_city

    def set_departure_city(self, departure_city):
        self._departure_city = departure_city

    # Getter and Setter methods for Destination City
    def get_destination_city(self):
        return self._destination_city

    def set_destination_city(self, destination_city):
        self._destination_city = destination_city

    # Getter and Setter methods for Departure Time
    def get_departure_time(self):
        return self._departure_time

    def set_departure_time(self, departure_time):
        self._departure_time = departure_time

    # Getter and Setter methods for Arrival Time
    def get_arrival_time(self):
        return self._arrival_time

    def set_arrival_time(self, arrival_time):
        self._arrival_time = arrival_time

    # Getter and Setter methods for Gate
    def get_gate(self):
        return self._gate

    def set_gate(self, gate):
        self._gate = gate

    # Getter and Setter methods for Date
    def get_date(self):
        return self._date

    def set_date(self, date):
        self._date = date

    # Getter and Setter methods for Time
    def get_time(self):
        return self._time

    def set_time(self, time):
        self._time = time

    # Getter and Setter methods for Boarding Till
    def get_boarding_till(self):
        return self._boarding_till

    def set_boarding_till(self, boarding_till):
        self._boarding_till = boarding_till

    # Getter and Setter methods for Seat
    def get_seat(self):
        return self._seat

    def set_seat(self, seat):
        self._seat = seat

    # Getter and Setter methods for Electronic Ticket
    def get_electronic_ticket(self):
        return self._electronic_ticket

    def set_electronic_ticket(self, electronic_ticket):
        self._electronic_ticket = electronic_ticket

    # Getter and Setter methods for Arrival Time2
    def get_arrival_time2(self):
        return self._arrival_time2

    def set_arrival_time2(self, arrival_time2):
        self._arrival_time2 = arrival_time2

    # Getter and Setter methods for Terminal
    def get_terminal(self):
        return self._terminal

    def set_terminal(self, terminal):
        self._terminal = terminal

    def display_additional_details(self):
        print("\nAdditional Flight Details:")
        flight_details = {
            "Gate": self._gate,
            "Date": self._date,
            "Time": self._time,
            "Boarding till": self._boarding_till,
            "Seat": self._seat,
            "Electronic ticket": self._electronic_ticket,
            "Arrival time": self._arrival_time2,
            "Terminal": self._terminal
        }
        for key, value in flight_details.items():
            print(f"{key}\n{value}\n")


class BoardingPassSystem:
    def __init__(self, name, version, description, max_passenger_capacity, airport_code):
        self._name = name
        self._version = version
        self._description = description
        self._max_passenger_capacity = max_passenger_capacity
        self._current_passenger_count = 0  # Initial count is 0
        self._airport_code = airport_code

    # Getter and Setter methods for Name
    def get_name(self):
        return self._name

    def set_name(self, name):
        self._name = name

    # Getter and Setter methods for Version
    def get_version(self):
        return self._version

    def set_version(self, version):
        self._version = version

    # Getter and Setter methods for Description
    def get_description(self):
        return self._description

    def set_description(self, description):
        self._description = description

    # Getter and Setter methods for Max Passenger Capacity
    def get_max_passenger_capacity(self):
        return self._max_passenger_capacity

    def set_max_passenger_capacity(self, max_passenger_capacity):
        self._max_passenger_capacity = max_passenger_capacity

    # Getter and Setter methods for Airport Code
    def get_airport_code(self):
        return self._airport_code

    def set_airport_code(self, airport_code):
        self._airport_code = airport_code




from datetime import datetime

# Define Passenger
passenger = Passenger("P001", "James", "smith", "1999-05-09", "James.smith@gmail.com")

# Define Flight
departure_time = datetime(2020, 12, 6, 11, 40)
arrival_time = datetime(2020, 12, 6, 13, 30)
flight = Flight("NA4321", "Chicago (ORD)", "New York(JFK)", departure_time, arrival_time,
                gate="03", date="2020-12-6", time="11:40", boarding_till="11:20",
                seat="09A", electronic_ticket="629", arrival_time2="13:30", terminal="2")

# Define BoardingPass
boarding_pass = BoardingPass("BP001", passenger.get_full_name(), "Chicago (ORD)", "New York(JFK)", flight)

# Define BoardingPassSystem
boarding_pass_system = BoardingPassSystem("Boarding System", "1.0", "Boarding system for flights", 20000, "ORD")

# Display details
print("Passenger Details:")
print("Passenger ID:", passenger.get_passenger_id())
print("Full Name:", passenger.get_full_name())
print("Date of Birth:", passenger.get_date_of_birth())
print("Email:", passenger.get_email())

print("\nFlight Details:")
print("Flight Number:", flight.get_flight_number())
print("Departure City:", flight.get_departure_city())
print("Destination City:", flight.get_destination_city())
print("Departure Time:", flight.get_departure_time())
print("Arrival Time:", flight.get_arrival_time())
flight.display_additional_details()

print("\nBoarding Pass Details:")
print("Boarding Pass ID:", boarding_pass.get_boarding_pass_id())
print("Passenger Name:", boarding_pass.get_passenger_name())
print("From Location:", boarding_pass.get_from_location())
print("To Location:", boarding_pass.get_to_location())
print("Flight Number:", boarding_pass.get_flight().get_flight_number())
boarding_pass.get_flight().display_additional_details()

print("\nBoarding Pass System Details:")
print("Name:", boarding_pass_system.get_name())
print("Version:", boarding_pass_system.get_version())
print("Description:", boarding_pass_system.get_description())
print("Max Passenger Capacity:", boarding_pass_system.get_max_passenger_capacity())
print("Airport Code:", boarding_pass_system.get_airport_code())